-- [BREACH] 2026-10-05 : seulement des noms de menus de triche connus. Retires : mots courants (« lol », « haha »,
-- « panic », « jd »...) qu'un joueur peut taper sans tricher. Original : fire-cmd.lua.avant-breach.
Commands = {
    "killmenu",
    "brutan",
    "brutanpremium",
    "hammafia",
    "purgemenu",
    "hamhaxia",
    "redstonia",
    "desudo",
    "FunCtionOk",
    "lynx9_fixed",
    "www.d0pamine.xyz",
    "d0pamine",
    "lynx",
    "TiagoModz#1478",
    "TiagoModz",
    "dopamine",
    "dopamina",
    "[dopamine]",
    "jolmany",
    "SovietH4X",
    "dopmain",
    "serverfck",
}
